### ISSUE TITLE
No way to use popup for usernames with spaces

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#13]
When you type @username peter - and there are more than 5 users with name "username", there is no way to find "username peter", because when you add space, the popup disapears

**Comment by Eldenroot** [comment]
@martec - does automention support full text searching? I cannot test it right now because I am away from home... thx!

**Comment by Eldenroot** [comment]
OK, it does not... anyway it should be possible because "Quick reference" plugin from Shade does full text search... it could fix this issue.

**Comment by martec** [comment]
about space check this post https://community.mybb.com/thread-173199-post-1364815.html#pid1364815

**Comment by Eldenroot** [comment]
Thanks! I will try
