### ISSUE TITLE
Add fallback if the avatar is not available (broken, invalid url, ...)

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#14]
There should be a fallback for broken avatars - it shoul show default avatar intead of the broken one

![bug_automenion](https://cloud.githubusercontent.com/assets/778890/22701863/2f541b72-ed5f-11e6-92db-843d5e040168.png)

**Comment by Eldenroot** [comment]
@martec - is this possible? Add some CSS/Js magic?

**Comment by martec** [comment]
about fallback check this post https://community.mybb.com/thread-173199-post-1364815.html#pid1364815
Ps. No setting in ACP

**Comment by Eldenroot** [comment]
Thank you!
