### ISSUE TITLE
Continue support?

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#15]
Hi  @martec - this is a really handy plugin. Do you plan to keep support?

I use DVZ mentions with user ID mentioning (to have updated usernames). Can you please update the plugin to follow this? Also Full text or avatar fallback would be great! :)

DVZ mentions is quite favourite plugin and it has missing automention feature whic his highly requested, this could be a really cool if you can continue in development :) thank you!

**Comment by martec** [comment]
Hi,

about ID check this post https://community.mybb.com/thread-173199-post-1362516.html#pid1362516

About support is kind of complicated, because At.js is no longer supported. https://github.com/ichord/At.js

**Comment by Eldenroot** [comment]
I know about at.js that was abandoned.

Anyway it works fine, with the latest at.js also special characters works (ě,š,č,ř,ž etc.)

I use DVZ mentions with this pattern: @"username"#123 - is possible to edit automention to use "" symbols for parsing? 

Also I would be really like if this automention would be compatible with Quick reference plugin from Shade

**Comment by martec** [comment]
hi,

check the version of link above... 
`about ID check this post https://community.mybb.com/thread-173199-post-1362516.html#pid1362516`

**Comment by Eldenroot** [comment]
Nevermind it...

**Comment by Eldenroot** [comment]
@martec - what about to use this library? https://github.com/zurb/tribute

**Comment by martec** [comment]
about tribute I already use this in the phpbb version.
the only problem that changes to this, in "quick edit" this will not work.

**Comment by Eldenroot** [comment]
Quick edit - hmm, I see. Maybe someone can help to fix this from MyBB community or is it a problem with MyBB itself?

I would like to use this version (if you will release it in future) - still better to have a working automention in new post/thread/pm and quick reply than nothing :)

**Comment by martec** [comment]
Closed.
for now the development will continue to be done in at.js as was discussed in another ticket.
