### ISSUE TITLE
Full-text support

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#18]
At.js library supports this - here is an example

![image](https://user-images.githubusercontent.com/778890/111497860-bc7f1080-8741-11eb-87e8-bccf1b02b450.png)

http://ichord.github.io/At.js/

P.S. I wanted to send you a PM but there is no other way how to contact you :)

**Comment by Eldenroot** [comment]
@martec - I have a working code for this (thank you @lairdshaw for your help (as always!) 

check this (it is based ony our latest veresion):
https://github.com/Eldenroot/automention/commit/0b26cf3696e881e21cae399e680464b42d3596d5

Maybe more will come :)

**Comment by martec** [comment]
Thanks! and @lairdshaw too thanks for help.

done here: https://community.mybb.com/thread-173199-post-1364920.html#pid1364920

i will close this. if you have more to add please create another ticket.
