### ISSUE TITLE
Javascript error when no SCEditor exists (e.g., not logged in)

### ISSUE THREAD

**Issue by lairdshaw** [martec/automention#26]
The conditional on line 83 of `jscripts/automention/automention.js` is slightly wrong (my fault, I think):

https://github.com/martec/automention/blob/2e2d3e02b5bba94adc240199f51c6fce8b47602e/jscripts/automention/automention.js#L83

Suggested replacement (tested somewhat):
```php
		if (typeof $('#message, #signature').sceditor("instance").getBody === 'function') {
```

The effect of the mistaken conditional is that when there is no SCEditor instance, such as when viewing thread pages anonymously (i.e., not logged in), a console error such as the following is shown:
```
Uncaught TypeError: $(...).sceditor(...).getBody is not a function
    <anonymous> https://domain.tld/forums/jscripts/automention/automention.js?ver=1.3.10:85
```

**Comment by martec** [comment]
Hi,

thank you for bug report. This mistake it's mine, because this part code has existed since the first version. 
fixed in 1.3.11. And thanks for fix.
