### ISSUE TITLE
Fulltext search minor issue

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#27]
I think it should start search for usernames which start with "El" and then go through others.

Check this - I wanna find "Eldenroot" - so I typed "el" -> it displays first users with "el" 

![image](https://user-images.githubusercontent.com/778890/164988197-3f9f67c3-090f-4b91-9e3a-279767415997.png)

BUT it should prioritise the usernames which match at the beginning first in my opinion (same behaviour like GitHub)

![image](https://user-images.githubusercontent.com/778890/164988285-42318000-bb67-48da-81ae-9cc49cb63574.png)

@lairdshaw you did check the library code in past, is that possible?

**Comment by lairdshaw** [comment]
@Eldenroot, we have the "Support full-text search?" setting which allows you to choose one or the other approach. The only enhancement we could make is to the first mode (searching only at the beginning of usernames), per your request above: in the list, after showing beginning-first matches, it could then show anywhere-in-word matches too where the limit hasn't yet been reached.

**Comment by lairdshaw** [comment]
Rereading your issue title+message, I see you were already aware of that setting, and seemed to want to implement those semantics on the fulltext mode, whereas I was thinking of implementing them on the non-fulltext mode - changing it to a "beginning matches first followed by anywhere matches" mode, since the fulltext mode already includes all matches.

**Comment by lairdshaw** [comment]
Implemented per your request, @Eldenroot. Please test and share your feedback.

**Comment by Eldenroot** [comment]
Give me 2 days, I am not at home. Thx for the fix

**Comment by Eldenroot** [comment]
OK:
1) issues with some usernames - no popup for "Eldenroot" if i type "Eld"
![image](https://user-images.githubusercontent.com/778890/165995862-aad3eb50-fb65-4c92-b635-23a23249cb16.png)

2) but when I write "ldenroot" all is fine
![image](https://user-images.githubusercontent.com/778890/165996009-d926efa2-4d61-4420-a59f-e301ca63810c.png)
 or whatever else
![image](https://user-images.githubusercontent.com/778890/165996060-4281c43b-7ffd-4799-b64f-57dc1bade4bd.png)


I dont see this with other usernames, just with mine...

**Comment by lairdshaw** [comment]
As I wrote in the PR's comments, I can't reproduce this, so:

> Can you please open Web Developer Tools and check what the return of the AJAX query is when you type out the start of your username - and whether there even is a query being made to your server?

**Comment by Eldenroot** [comment]
Thread contributors works fine 
![image](https://user-images.githubusercontent.com/778890/166097724-0ad43860-fb73-4081-a84a-b3cbc81895c8.png)

**Comment by Eldenroot** [comment]
OK, another clue:
- none user with "E" at the beginning of the username is not displayed (I have over 30 users with this pattern). 

@lairdshaw - I can open the console and check it but it would be much easier to discuss this via Discord.

I think it bugs this user 
![image](https://user-images.githubusercontent.com/778890/166098161-ee39ec28-e499-486d-baee-8f4863632a5b.png)
