### ISSUE TITLE
Special letters are not supported

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#29]
If you wanna mention anybody with special letter in the username, the search is not working.

I mean this:

Š, Č, Ě, Ž, Ň, É, Ý, Á, Í etc.

**Comment by martec** [comment]
probably the improvements in the new versions brought back the problem of the past already solved.
https://community.mybb.com/thread-173199-post-1170601.html#pid1170601

fixed used in 1.2

https://github.com/martec/automention/commit/fdb88c5e1bc1be29a873dc6ddd5c2510cc50633d

Sorry but I don't have the patience to try to find why...

**Comment by Eldenroot** [comment]
OK
