### ISSUE TITLE
Minlength 2 instead of 3

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#7]
In MyBB v1.8.7 there will be minimum length for autocomplete set to 2 (was 3).

Maybe it would be nice to have this also in your plugin

https://github.com/mybb/mybb/issues/1567

**Comment by martec** [comment]
ok after release of 1.8.7 i will release new version compatible with 1.8.7

**Comment by martec** [comment]
http://community.mybb.com/thread-173199-post-1211720.html#pid1211720
